[["file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/process/Tests/ProcessFailedExceptionTest.php",{"_uri":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/process/Tests/ProcessFailedExceptionTest.php","_root":{"kind":4096,"name":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/process/Tests/ProcessFailedExceptionTest.php","location":{"uriHash":2000936923,"range":{"start":{"line":0,"character":0},"end":{"line":137,"character":0}}},"children":[{"kind":512,"name":"Symfony\\Component\\Process\\Tests","location":{"uriHash":2000936923,"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":42}}}},{"kind":1,"name":"TestCase","location":{"uriHash":2000936923,"range":{"start":{"line":13,"character":4},"end":{"line":13,"character":30}}},"modifiers":4096,"associated":[{"kind":1,"name":"PHPUnit\\Framework\\TestCase"}]},{"kind":1,"name":"ProcessFailedException","location":{"uriHash":2000936923,"range":{"start":{"line":14,"character":4},"end":{"line":14,"character":62}}},"modifiers":4096,"associated":[{"kind":1,"name":"Symfony\\Component\\Process\\Exception\\ProcessFailedException"}]},{"kind":1,"name":"Symfony\\Component\\Process\\Tests\\ProcessFailedExceptionTest","location":{"uriHash":2000936923,"range":{"start":{"line":19,"character":0},"end":{"line":136,"character":1}}},"children":[{"kind":32,"name":"testProcessFailedExceptionThrowsException","location":{"uriHash":2000936923,"range":{"start":{"line":24,"character":4},"end":{"line":39,"character":5}}},"doc":{"description":"tests ProcessFailedException throws exception if the process was successful.","type":""},"modifiers":1,"type":"","children":[],"scope":"Symfony\\Component\\Process\\Tests\\ProcessFailedExceptionTest"},{"kind":32,"name":"testProcessFailedExceptionPopulatesInformationFromProcessOutput","location":{"uriHash":2000936923,"range":{"start":{"line":45,"character":4},"end":{"line":89,"character":5}}},"doc":{"description":"tests ProcessFailedException uses information from process output\nto generate exception message.","type":""},"modifiers":1,"type":"","children":[],"scope":"Symfony\\Component\\Process\\Tests\\ProcessFailedExceptionTest"},{"kind":32,"name":"testDisabledOutputInFailedExceptionDoesNotPopulateOutput","location":{"uriHash":2000936923,"range":{"start":{"line":95,"character":4},"end":{"line":135,"character":5}}},"doc":{"description":"Tests that ProcessFailedException does not extract information from\nprocess output if it was previously disabled.","type":""},"modifiers":1,"type":"","children":[],"scope":"Symfony\\Component\\Process\\Tests\\ProcessFailedExceptionTest"}],"associated":[{"kind":1,"name":"PHPUnit\\Framework\\TestCase"}],"modifiers":0}]},"_hash":2000936923}]]